### ISSUE TITLE
$DESKTOP_SESSION not set resulting in "AttributeError: 'NoneType' object has no attribute 'lower'"

### ISSUE THREAD

**Issue by daniel-Jones** [kanishka-linux/kawaii-player#10]
$DESKTOP_SESSION isn't set within my environment, resulting in the error:

File "/usr/share/kawaii-player/stylesheet.py", line 13, in __init__
    desktop_session = desktop_session.lower()
AttributeError: 'NoneType' object has no attribute 'lower'

Temporarily bypassed by removing the if/else line 11-15, replacing it with desktop_session = 'lxde' (create a default case if NoneType).

Distro: Arch
wm: i3

**Comment by kanishka-linux** [comment]
thanks, fixed!

**Comment by kanishka-linux** [comment]
By the way is there any issue adding media, as mentioned in the e-mail? You just have to add library and update the collection.

**Comment by daniel-Jones** [comment]
haha nah I had figured it out shortly after opening the ticket, UI is just slightly confusing initially. Cheers.

**Comment by kanishka-linux** [comment]
ok great then. I hope you'll enjoy the program.
