### ISSUE TITLE
Add support for youtube-dl sites

### ISSUE THREAD

**Issue by Joseph65** [kanishka-linux/kawaii-player#12]
it would be nice to have support for playback of youtube-dl supported sites https://rg3.github.io/youtube-dl/supportedsites.html .
Like mpv it has support using the ytdl option, or mplayer using youtube-dl.
kawaii-player "Open Url" option doesn't open a twitch stream for example.

**Comment by kanishka-linux** [comment]
I'm also thinking about it for quite some time. Integrating all these external url's into local library will take time; but I think, it is possible to implement some quick fix for "Open Url" functionality, without adding them to local playlist/library.

**Comment by kanishka-linux** [comment]
As expected, quick fix was possible. I've added some commits in devel branch. Open Url in playlist section should now work with ytdl supported sites.

**Comment by kanishka-linux** [comment]
v2.8 has pretty good support for ytdl. One can even use internal youtube browser to navigate to any ytdl supported site and can open links with kawaii-player. Casting of ytdl links is also supported via web interface.
