### ISSUE TITLE
IPTV M3u Playlists

### ISSUE THREAD

**Issue by nonameaccount** [kanishka-linux/kawaii-player#16]
First off, I want to commend you on the excellent application. It has become my favorite media player on Linux. I have a question about playlists. I have an IPTV subscription and if I open the provided URL with mpv alone, I can play the streams, but I do not have access to the playlist directly. In order to play a different station, I have to advance the playlist manually one channel at a time until I get where I want to be. No fun when there are over 3000 stations. With your application, when I load the URL, it plays the first channel, but I haven't been able to figure out how to move through the playlist. Is there a set of directions I have overlooked in the readme or is this functionality not possible?

**Comment by kanishka-linux** [comment]
Is it possible to save playlist locally as m3u file? 

If it can be saved, then follow **PlayLists->Open File**, after that all playlist entries should be available in playlist column. Initially playlist will be saved as TMP_PLAYLIST, which you can rename later.
