### ISSUE TITLE
[Feature request]: External audio

### ISSUE THREAD

**Issue by isvladxxe** [kanishka-linux/kawaii-player#18]
The Russian anime community has a terrible disease: it does not like to attach sound tracks inside the container.
- It would be nice to add an external soundtrack selection
- It would be ideal to pick up automatically, setting the path by mask
`./{LANG Sound}/{DUBER}/{episode regex}`

 - I can help, but have no experience in python
- It can be done by addon?

**Comment by kanishka-linux** [comment]
Adding support for automatically picking external audio is somewhat tricky and may need some good amount of changes. 

However, manually adding external tracks was possible with few lines of code, so added support for it. 

Build from latest master branch.
 
Go to `Preferences->Shortcuts` and add shortcut `custom-key add-external-audio`.  
eg `ctrl+g add-external-audio` , save changes and restart application. 
Once video is playing, press key `ctrl+g`, and select external audio files.

About addons, currently one can't add new internal functions to the application using them.
