### ISSUE TITLE
How to play videos

### ISSUE THREAD

**Issue by sevu** [kanishka-linux/kawaii-player#19]
Hello folks,

as simple as it sounds, I couldn't find how to play Video files with this application – I.e. playing in sense of playing a video file in the current folder like one does with mpv and such.

Best wishes, Sevu

**Comment by kanishka-linux** [comment]
There are multiple ways to do it. 

1. Open application and simply drag and drop video files into it `OR`,

2. Go-To playlist section, create playlist and add items into it manually `OR`,

3. Add local video directory path to `library`, update database in `Video` section, and get everything inside video section with different categories.
