### ISSUE TITLE
Torrent streaming is not working on linux mint 18.1

### ISSUE THREAD

**Issue by AndersonFirmino** [kanishka-linux/kawaii-player#2]
Torrent streaming don't work on linux mint 18.1 x64 

```
/usr/lib/python3/dist-packages/libtorrent.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZN5boost4asio2ip10address_v4C1ERKNS_5arrayIhLm4EEE
```

**Comment by kanishka-linux** [comment]
It's working well on Arch and Ubuntu 16.04. I think, from the output, it might be a problem with python3-libtorrent bindings packaged for mint.

**Comment by kanishka-linux** [comment]
Recently I've tested the torrent streaming feature on linux mint 18.1 x64 with xfce edition, and it was working fine. I think you might have encountered some incompatible dependency problem, or some dependencies might not have been installed properly. Therefore, use **gdebi** from command line to install the package.
