### ISSUE TITLE
server available in mobile browser, but seems to serve only 127.0.0.1: urls

### ISSUE THREAD

**Issue by simlei** [kanishka-linux/kawaii-player#22]
Hi,
I just did a fresh install via .deb.
Most stuff just works! Great job!

But - when I access the media server from my mobile phone, there is something odd. See this screenshot below. When I downloaded the m3u playlist, all urls in there (on the phone!) seemed to point to 127.0.0.1: (see second screenshot, after opening that url)

I accessed the media server via the local network address. Is this intended behavior, e.g. always serve 127.0.0.1: addresses? That can't be right ^^

![image](https://user-images.githubusercontent.com/982379/69759438-6c51f880-1162-11ea-9ef2-aa7f57c71776.png)
![image](https://user-images.githubusercontent.com/982379/69759451-72e07000-1162-11ea-8378-cde0f2576379.png)

**Comment by simlei** [comment]
Oh, never mind. I figured out how to get to the correct setting... :)

**Comment by kanishka-linux** [comment]
Can you elaborate what was the problem and how did you fix it? It will be good to have it for future reference when someone else is also facing similar issue.

**Comment by simlei** [comment]
Gladly.

What worked already: 
- stream a playlist so that my PC at 127.0.0.1:9001 got a connection
- The buttton to do so is seen belo

What did not work:
- I *opened port 9001 for my local network* and tried to access the local IP:9001 with my smartphone. A site did load, but with bad media embedded. clearly, resource URLs were garbled

Resolution: 

as seen here, change the value of the selected field in the gif to the exact address you will be typing in your browser.

![Peek 2019-11-28 14-44](https://user-images.githubusercontent.com/982379/69811133-b633f080-11ed-11ea-8786-ce6d3dfbf377.gif)

Room for improvement:

- as far as I know, websites can detect how the client connects, and accordingly serve their urls.

**Comment by kanishka-linux** [comment]
Yes, that is the expected behaviour. Local stream IP and the address that one uses in the browser needs to be same and also it should be local LAN IP address, to get the valid playlist from browser. 

I'll see if it can be done in a somewhat better way.

Thanks for the detailed reply.
