### ISSUE TITLE
How to open the application?

### ISSUE THREAD

**Issue by null15** [kanishka-linux/kawaii-player#28]
I'm on 64-bit Windows 10, I tried following installation but I'm SOOO confused. This was the last step I did, but I can't find any application (.exe) to run. 
![image](https://user-images.githubusercontent.com/30800470/98888094-8bdb5180-2497-11eb-8400-89642f763eae.png)

**Comment by kanishka-linux** [comment]
once you extract the archive, you'll see `kawaii_player` file in the extracted `directory`. I think, windows doesn't show `.exe` extension. You just need to click on the `kawaii_player` binary file, application should open.

**Comment by null15** [comment]
> once you extract the archive, you'll see `kawaii_player` file in the extracted `directory`. I think, windows doesn't show `.exe` extension. You just need to click on the `kawaii_player` binary file, application should open.

There is only a bunch of .py files

"C:\Users\null\Desktop\Kawaii Player\kawaii-player\kawaii_player"
![image](https://user-images.githubusercontent.com/30800470/99442959-68425c00-291a-11eb-973f-3e974cf6bdc5.png)

**Comment by kanishka-linux** [comment]
use this link to download self contained binary. 
It is in releases: https://github.com/kanishka-linux/kawaii-player/releases/download/v4.2.0-1/kawaii-player-4.2.0-1.windows10.x86_64-bin.7z

**Comment by null15** [comment]
> use this link to download self contained binary.
> It is in releases: https://github.com/kanishka-linux/kawaii-player/releases/download/v4.2.0-1/kawaii-player-4.2.0-1.windows10.x86_64-bin.7z

Worked, thanks a ton.
