### ISSUE TITLE
Cannot start in kawaii-player in arch

### ISSUE THREAD

**Issue by mkultravictimx** [kanishka-linux/kawaii-player#34]
I installed the kawaii-player from the AUR and its dependices and then when I tried to start it through terminal it spat out this and nothing happened I am using kde plasma in arch
`/usr/lib/python3.10/site-packages/kawaii_player kawaii_player.py /home/jaiden
['/usr/lib/python3.10/site-packages/kawaii_player', '/usr/bin', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/home/jaiden/.local/lib/python3.10/site-packages', '/usr/lib/python3.10/site-packages']
--using pycurl--
QTWEBENGINE
Using QTWEBENGINE
/home/jaiden/.config/kawaii-player/tmp posix
taglib --tagging-module--
DEBUG:OpenGL.platform.ctypesloader:Loaded libGL.so => libGL.so.1 <CDLL 'libGL.so.1', handle 556c6dd279f0 at 0x7f2dc619dc30>
INFO:OpenGL.acceleratesupport:No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
libvlc not detected
posix openbox-kde
1920 1080
1080 1920
not enough values to unpack (expected 2, got 1) wrong values in config file
INFO::kawaii_player::update_video_dict_criteria: {'anime': 'Anime', 'movies': 'Movies', 'tv shows': 'TV Shows', 'cartoons': 'Cartoons', 'others': 'Others'}::['Anime', 'Movies', 'TV Shows', 'Cartoons', 'Others']::--1808--
INFO:kawaii_player.kawaii_player:{'anime': 'Anime', 'movies': 'Movies', 'tv shows': 'TV Shows', 'cartoons': 'Cartoons', 'others': 'Others'}::['Anime', 'Movies', 'TV Shows', 'Cartoons', 'Others']::--1808--
QLayout: Attempting to add QLayout "" to ExtraToolBar "frame_extra_toolbar", which already has a layout
QLayout: Attempting to add QLayout "" to ExtraToolBar "frame_extra_toolbar", which already has a layout
QLayout: Attempting to add QLayout "" to ExtraToolBar "frame_extra_toolbar", which already has a layout
QLayout: Attempting to add QLayout "" to ExtraToolBar "frame_extra_toolbar", which already has a layout
DEBUG::kawaii_player::main: #BROWSER_BACKEND=QTWEBENGINE,QTWEBKIT
DEBUG:kawaii_player.kawaii_player:#BROWSER_BACKEND=QTWEBENGINE,QTWEBKIT
DEBUG::kawaii_player::main: #GET_LIBRARY=pycurl,curl,wget
DEBUG:kawaii_player.kawaii_player:#GET_LIBRARY=pycurl,curl,wget
DEBUG::kawaii_player::main: #IMAGE_FIT_OPTION=0-9
DEBUG:kawaii_player.kawaii_player:#IMAGE_FIT_OPTION=0-9
DEBUG::kawaii_player::main: #YTDL_PATH=default,automatic
DEBUG:kawaii_player.kawaii_player:#YTDL_PATH=default,automatic
INFO::kawaii_player::main: mpv_conf: False
INFO:kawaii_player.kawaii_player:mpv_conf: False
DEBUG::kawaii_player::main: #THEME=default,system,dark
DEBUG:kawaii_player.kawaii_player:#THEME=default,system,dark
DEBUG::kawaii_player::main: #EXTRA_PLAYERS=vlc,kodi etc..
DEBUG:kawaii_player.kawaii_player:#EXTRA_PLAYERS=vlc,kodi etc..
DEBUG::kawaii_player::main: #GLOBAL_FONT=Name of Font
DEBUG:kawaii_player.kawaii_player:#GLOBAL_FONT=Name of Font
DEBUG::kawaii_player::main: #THUMBNAIL_TEXT_COLOR/LIST_TEXT_COLOR=red,green,blue,yellow, gray,white,black,cyan,magenta,darkgray,lightgray,darkred, darkblue,darkyellow,transparent
DEBUG:kawaii_player.kawaii_player:#THUMBNAIL_TEXT_COLOR/LIST_TEXT_COLOR=red,green,blue,yellow, gray,white,black,cyan,magenta,darkgray,lightgray,darkred, darkblue,darkyellow,transparent
DEBUG::kawaii_player::main: #For Dark Theme, use lightgray, if white color looks bright
DEBUG:kawaii_player.kawaii_player:#For Dark Theme, use lightgray, if white color looks bright
DEBUG::kawaii_player::main: Nimbus Sans14
DEBUG:kawaii_player.kawaii_player:Nimbus Sans14
DEBUG::stylesheet::apply_stylesheet: min-height-box=height: 39px
DEBUG:kawaii_player.kawaii_player:min-height-box=height: 39px
DEBUG::stylesheet::apply_stylesheet: min-height-box=height: 39px
DEBUG:kawaii_player.kawaii_player:min-height-box=height: 39px
DEBUG::stylesheet::apply_stylesheet: min-height-box=height: 39px
DEBUG:kawaii_player.kawaii_player:min-height-box=height: 39px
0 0
plugins
(5, 0, 0, 1) > (0, 0, 0, 0)
Addons loading ....
Addons loading ....
Addons loading ....
Addons loading ....
<class 'str'> MyServer --addon-changed--
<class 'MyServer.MyServer'> MyServer --addon-changed--
MyServer select
MyServer
['Login', 'Logout', 'Discover', 'History', 'newversion']
MyServer 0 ==site_index
Video video
-1 0
1 --dock-option---
75497482
Event Filter Installed in new_tray_widget
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/kawaii_player/widgets/thumbnail.py", line 109, in resizeEvent
    self.setMaximumHeight(2.5*ui.height_allowed)
TypeError: setMaximumHeight(self, int): argument 1 has unexpected type 'float'
Aborted (core dumped)
`

**Comment by kanishka-linux** [comment]
looks like latest qt has some breaking changes which requires int as an argument to `setMaximumHeight`.
I don't have access to arch setup right now. What you can do is, in the line 109 of `thumbnail.py`, try `int(2.5 * ui.height_allowed)`. And then build from source again.

**Comment by mkultravictimx** [comment]
I actually distro hopped recently to an ubuntu based distro and its working!

**Comment by nzer0ne** [comment]
> looks like latest qt has some breaking changes which requires int as an argument to `setMaximumHeight`. I don't have access to arch setup right now. What you can do is, in the line 109 of `thumbnail.py`, try `int(2.5 * ui.height_allowed)`. And then build from source again.

Worked like a charm

**Comment by kanishka-linux** [comment]
[fixed](https://github.com/kanishka-linux/kawaii-player/commit/496abffe7d3bf626e28859976fed117e758b7b6e)

**Comment by stratosgear** [comment]
It would be great if we made another release so this fix can be picked up for arch users! :)

**Comment by eclairevoyant** [comment]
@stratosgear you can always use the git version instead
