### ISSUE TITLE
Don't require QT5

### ISSUE THREAD

**Issue by DUOLabs333** [kanishka-linux/kawaii-player#35]
I'm planning to use the web interface only, and so, don't need the GUI features. Is there a way to just load up a TUI or web interface?

**Comment by kanishka-linux** [comment]
yes, one can start the player in headless mode using `xvfb` - on linux based systems. Not sure if there is any alternative available in windows or OSX.

check this [section](https://github.com/kanishka-linux/kawaii-player#media-server) for more details

**Comment by DUOLabs333** [comment]
Yes, but it still requires me to have pyqt5 installed.

**Comment by kanishka-linux** [comment]
Yes, PyQt5 is hard required dependency for the entire application. Currently media server and GUI are tightly coupled.
I also thought about de-coupling media server at one time, but it will require deep refactor.
It is on my mind, but not sure when will I pick it up.
