### ISSUE TITLE
Cannot run on ubuntu 22.04

### ISSUE THREAD

**Issue by woyaojizhu8** [kanishka-linux/kawaii-player#43]
Cannot find libavcodec.so.59

**Comment by kanishka-linux** [comment]
I'm able to run it on ubuntu 22.04 (on raspberry-pi).

I've written [this script](https://github.com/kanishka-linux/rpi-utilities/blob/master/rpiscript.py) to install kawaii-player on raspberry-pi - which ideally should work for any debian based distro with little bit of tweaking maybe.
