### ISSUE TITLE
torrent support - broken python bindings

### ISSUE THREAD

**Issue by ShalokShalom** [kanishka-linux/kawaii-player#6]
```
[matthias@cosmos kawaii-player]$ kawaii-player 
/usr/share/kawaii-player kawaii_player.py /home/matthias/Documents/makepkg/kawaii-player
['/usr/share/kawaii-player', '/usr/share/kawaii-player', '/usr/lib/python36.zip', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload', '/usr/lib/python3.6/site-packages']
--using default pycurl--
file_not_exists
Using QTWEBENGINE
/home/matthias/.config/kawaii-player/tmp posix
taglib --tagging-module--
No module named 'libtorrent'
posix /usr/share/xsessions/plasma
768 1366
303 --width--allowed--
Could not parse stylesheet of object 0x238c5d0
addons loading....
addons loading....
addons loading....
0 0
plugins
(1, 1, 1, 0) > (0, 0, 0, 0)
Addons loading ....
Addons loading ....
Addons loading ....
<class 'str'> Shoutcast --addon-changed--
<class 'Shoutcast.Shoutcast'> Shoutcast --addon-changed--
Shoutcast select
Shoutcast
['History', 'Genre']
Shoutcast 0 ==site_index
Video video
-1 0
1 --dock-option---
111149067
Event Filter Installed in new_tray_widget
Could not parse stylesheet of object 0x238c5d0
Could not parse stylesheet of object 0x23e02c0
[1, 1]
Could not parse stylesheet of object 0x2706b30


```

I get this message via OSD: 

"python3 bindings for libtorrent are broken
Torrent Streaming feature will be disabled"

Which packages are probably meant?

**Comment by kanishka-linux** [comment]
If you're using ubuntu then the package is python3-libtorrent. In archlinux package is libtorrent-rasterbar.

**Comment by kanishka-linux** [comment]
I just updated libtorrent-rasterbar in archlinux, and found that python3 bindings are broken in it.

**Comment by ShalokShalom** [comment]
Its build with libtorrent-rasterbar in KaOS.

**Comment by kanishka-linux** [comment]
Can you open python shell and type output of 'import libtorrent'

**Comment by ShalokShalom** [comment]
```
[matthias@cosmos ~]$ python3
Python 3.6.1 (default, Mar 22 2017, 21:57:16) 
[GCC 5.4.1 20170214] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import libtorrent
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'libtorrent'
>>> 


```

**Comment by kanishka-linux** [comment]
ok, most probably python3 bindings are not included in KaOS. Is it included separately in it?

**Comment by ShalokShalom** [comment]
How they are called?

**Comment by ShalokShalom** [comment]
KaOS ship in general like upstream does.

**Comment by kanishka-linux** [comment]
try searching python-libtorrent or python3-libtorrent using native package manager

**Comment by ShalokShalom** [comment]
I mean the actual file.

**Comment by ShalokShalom** [comment]
Both not available in our repos at all. Not included in any other package.

**Comment by kanishka-linux** [comment]
ok, let me search actual file

**Comment by kanishka-linux** [comment]
in archlinux, python3 bindings are included in libtorrent-rasterbar package.

**Comment by ShalokShalom** [comment]
found it: https://github.com/KaOSx/apps/blob/master/libtorrent-rasterbar/PKGBUILD

Its build with python2

Can try to rebuild with 3

**Comment by kanishka-linux** [comment]
ok, great. It should build with python3 with no problem.

**Comment by kanishka-linux** [comment]
You can also take a look at archlinux PKGBUILD 'https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/libtorrent-rasterbar'.

**Comment by ShalokShalom** [comment]
I already took a that one. Seems like i have to adopt it a bit more..

Can you say me, if i need to rebuild kawaii-player as well?

**Comment by kanishka-linux** [comment]
No, there is no need to rebuild kawaii-player.

**Comment by ShalokShalom** [comment]
ok, i adopt the Arch PKGBUILD for us and now does it work 

thanks a lot :+1:
