### ISSUE TITLE
Can't close program

### ISSUE THREAD

**Issue by luigino** [kanishka-linux/kawaii-player#8]
On openSUSE Tumbleweed, it remains running even after closing the main window.
Is there a hidden "quit" button elsewhere?

**Comment by kanishka-linux** [comment]
either use Tray icon context menu or u can also use  quit button in options column. Are u using plasma desktop? I was having such problem in it. In plasma, one has to un-hide tray icon menu, before it can be shown in tray panel. I've already written about it in troubleshooting section.

**Comment by luigino** [comment]
Thanks, I am indeed using plasma 5 and couldn't see the second tray icon.
